/*
 * FLIGHT_PARAMETERS_CONFIG.h
 *
 *  Created on: Apr 2, 2024
 *      Author: tommaso
 */

#ifndef FLIGHT_PARAMETERS_CONFIG_H
#define FLIGHT_PARAMETERS_CONFIG_H

#define ACCELEROMETER_MEASURE_TOLERANCE_MG	0
#define GYRO_MEASURE_TOLERANCE_MDPS			0

#endif /* INC_FLIGHT_PARAMETERS_CONFIG_H_ */
