/*
 * FLIGHT_PARAMETERS_CONFIG.h
 *
 *  Created on: Apr 2, 2024
 *      Author: tommaso
 */

#ifndef FLIGHT_PARAMETERS_CONFIG_H
#define FLIGHT_PARAMETERS_CONFIG_H

#define SENSORS_TASK_PERIOD 10U	/* Period of Sensors Task Period in TICKS */
#define FLASH_WRITE_TASK_PERIOD 80U
#define FLIGHT_FSM_TASK_PERIOD 10U
#define FLIGHT_HEALTH_CHECK_TASK_PERIOD 100U
#define COMMUNICATION_BOARD_TASK_PERIOD 100U

#define FLASH_NUMBER_OF_STORE_EACH_TIME (FLASH_WRITE_TASK_PERIOD / SENSORS_TASK_PERIOD)

#define ACCELEROMETER_MEASURE_TOLERANCE_MG	0
#define GYRO_MEASURE_TOLERANCE_MDPS			0
#define ACC_SENSOR_ERROR 0
#define VELOCITY_BOUND_TOUCHDOWN 3.0F
#define THRESHOLD 10
#define LIFT_OFF_ACC_THRESHOLD 1.5F
#define MAIN_DEPLOY_HEIGHT 100

#define LIFTOFF_SAFETY_COUNTER 10
#define COASTING_SAFETY_COUNTER 5
#define APOGEE_SAFETY_COUNTER 30
#define MAIN_SAFETY_COUNTER 5
#define TOUCHDOWN_SAFETY_COUNTER 100
#define MIN_TICK_COUNTS_BETWEEN_BURNING_APOGEE 1500

#endif /* INC_FLIGHT_PARAMETERS_CONFIG_H_ */
